import type { Metadata } from "next";
import { Bai_Jamjuree as BaiJamjuree, Inter, Roboto_Flex as Roboto } from "next/font/google";
import LeftComponent from "./components/LeftLayoutComponent";
import AuthProvider from "./components/authprovider/authprovider";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({ subsets: ['latin'], variable: '--font-roboto' })
const baiJamjuree = BaiJamjuree({ subsets: ['latin'], weight: '700', variable: '--font-bai-jamjuree' })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className= {`${roboto.variable} ${baiJamjuree.variable} font-sans w-full h-full bg-zinc-900 text-gray-200 `}>
        <AuthProvider>
          <div className="flex flex-row">
            <div>
              <LeftComponent />
            </div>
            <div>{children}</div>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
